### ISSUE TITLE
Use private case class constructor instead of standard class for public data structures

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-connectors#190]
In places like https://github.com/apache/incubator-pekko-connectors/blob/main/s3/src/main/scala/org/apache/pekko/stream/connectors/s3/model.scala we happen to use `class` instead of `case class` for public data structures due to the fact that with standard usage of `case class`, if you add more fields to the `case class` then it breaks binary compatibility (due to `unapply`/`copy`).

There is meant to be a better technique that involves a lot less boilerplate that achieves the same effect via usage of `private` constructors in a `case class` , see https://github.com/scala/improvement-proposals/pull/50#issuecomment-1346210753 .

One thing that should be verified is what the difference will be on a bytecode level (if there is a breaking difference then it should ideally be done before first release).

**Comment by mdedetrich** [comment]
@raboof @jrudolph Maybe you can provide any context as to why this was originally implemented using just a standard class? Maybe it was due to some earlier issues with `private` constructors in Scala and/or the `private` constructor works differently when called from Java vs Scala?

Or maybe it was just an oversight

**Comment by raboof** [comment]
It looks like it's a difference between Scala 2.13 and Scala 3 that in Scala 3 the generated `copy` method becomes private when the constructor is private - neat.

On Scala 2.13 the copy method remains public, so this pattern would not be binary compatible. We'd have to repeat the copy method to make it private.

At that point the choice is between:
1) using a class and implementing 'toString', 'equals', 'hashCode', and 'private copy' (for convenience), or
2) using a case class, making its constructor private and implementing 'apply', 'private unapply' and 'private copy'

I think, right? Indeed the case class approach seems to be less boilerplatey.

We sometimes cannot use case classes because case classes can't extend each other. There are also cases where we started with a case class (with public unapply/copy methods), and then had to convert to a regular class with a bunch of boilerplate to be able to add a field without breaking binary compatibility.

**Comment by mdedetrich** [comment]
> It looks like it's a difference between Scala 2.13 and Scala 3 that in Scala 3 the generated `copy` method becomes private when the constructor is private - neat.

Ahah!

I had a hunch I was missing something, indeed if the `copy` constructor is public up until Scala 3 then the technique won't work unless you override the copy method (which I personally think is an overall worse solution because it has a higher risk of you accidentally missing to do this).

> We sometimes cannot use case classes because case classes can't extend each other. There are also cases where we started with a case class (with public unapply/copy methods), and then had to convert to a regular class with a bunch of boilerplate to be able to add a field without breaking binary compatibility.

Indeed this is the primary motivator from my side. Thanks again for your insight, I am going to close this since its going to be some time until we support Scala 3.
